### ISSUE TITLE
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_encode_video2() error -1: Could not encode video packet.

### ISSUE THREAD

**Issue by khyatiChitroda** [vanevery/JavaCV_0.3_stream_test#7]
getting error at line: 
recorder.record(yuvImage);

2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:933)
2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:845)
2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:838)
2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at com.example.javacv.stream.test2.MainActivity$CameraView.onPreviewFrame(MainActivity.java:437)
2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221)
2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-14 14:13:42.990 7858-7858/com.example.javacv.stream.test2 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-05-14 14:13:42.991 7858-7858/com.example.javacv.stream.test2 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by iamkdblue** [comment]
@khyatiChitroda did you find any solution or alternative?

**Comment by gowthami77** [comment]
@khyatiChitroda @iamkdblue  did you find any solution or alternative?
